//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLaunch.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLaunch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_About {
            get {
                return ResourceManager.GetString("Command_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループを追加する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_AddGroup {
            get {
                return ResourceManager.GetString("Command_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目を追加する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_AddLaunchItem {
            get {
                return ResourceManager.GetString("Command_AddLaunchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクを追加する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_AddLink {
            get {
                return ResourceManager.GetString("Command_AddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_Cancel {
            get {
                return ResourceManager.GetString("Command_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_Creator {
            get {
                return ResourceManager.GetString("Command_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   寄付する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_Donate {
            get {
                return ResourceManager.GetString("Command_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションを終了する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_ExitApplication {
            get {
                return ResourceManager.GetString("Command_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区切り線を挿入する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_InsertSeparator {
            get {
                return ResourceManager.GetString("Command_InsertSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_No {
            get {
                return ResourceManager.GetString("Command_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_OK {
            get {
                return ResourceManager.GetString("Command_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   環境設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_Preferences {
            get {
                return ResourceManager.GetString("Command_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この項目を削除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_RemoveItem {
            get {
                return ResourceManager.GetString("Command_RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_Repository {
            get {
                return ResourceManager.GetString("Command_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリパスを選択する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_SelectDirectoryPath {
            get {
                return ResourceManager.GetString("Command_SelectDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルパスを選択する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_SelectFilePath {
            get {
                return ResourceManager.GetString("Command_SelectFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Command_Yes {
            get {
                return ResourceManager.GetString("Command_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_ActivateOn {
            get {
                return ResourceManager.GetString("Label_ActivateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Group {
            get {
                return ResourceManager.GetString("Label_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   線の色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_LaunchBorderColor {
            get {
                return ResourceManager.GetString("Label_LaunchBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   線の太さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_LaunchBorderSize {
            get {
                return ResourceManager.GetString("Label_LaunchBorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランチャー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Launcher {
            get {
                return ResourceManager.GetString("Label_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示項目設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_LaunchItemSettings {
            get {
                return ResourceManager.GetString("Label_LaunchItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランチャー設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_LaunchSettings {
            get {
                return ResourceManager.GetString("Label_LaunchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_LeftClick {
            get {
                return ResourceManager.GetString("Label_LeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Link {
            get {
                return ResourceManager.GetString("Label_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいグループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_NewGroup {
            get {
                return ResourceManager.GetString("Label_NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_RightClick {
            get {
                return ResourceManager.GetString("Label_RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区切り線 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Separator {
            get {
                return ResourceManager.GetString("Label_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   線が表示される位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_ShowLaunchBorder {
            get {
                return ResourceManager.GetString("Label_ShowLaunchBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   気に入って頂けましたら、継続開発のためのご寄付も歓迎いたします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_NotifyDonate {
            get {
                return ResourceManager.GetString("Message_NotifyDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランチャーに項目を追加しましょう。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_LaunchItemSettingsHint {
            get {
                return ResourceManager.GetString("Text_LaunchItemSettingsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランチャーに表示する項目を登録します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_LaunchItemSettingsTitle {
            get {
                return ResourceManager.GetString("Text_LaunchItemSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランチャーの設定を行います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_LaunchSettingsTitle {
            get {
                return ResourceManager.GetString("Text_LaunchSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この項目は区切り線として表示されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_SeparatorHint {
            get {
                return ResourceManager.GetString("Text_SeparatorHint", resourceCulture);
            }
        }
    }
}
